GET http://localhost:3000/api/notificaciones?usuarioId=2

###

POST http://localhost:3000/api/notificaciones
Content-Type: application/json

{
  "usuarioId": 2,
  "tipo": "solicitud_recibida",
  "mensaje": "Has recibido una nueva solicitud de amistad."
}

###

PUT http://localhost:3000/api/notificaciones/1
Content-Type: application/json

{}